# Site settings
title: GitForge URL Shortener
author: theriturajps
description: "A Jekyll & Javascript based GitForge URL Shortener for personal use"
url: "l.johng.io"
gitforge_link: "https://www.gitforge.in/"
gtag_id: 

# Change the primary color of the entire site
theme_color: "#317b71"

# Build settings
markdown: kramdown
permalink: pretty

# Collection definitions and settings
collections:
  links:
    output: true
    permalink: /:path/


# Set default layout for link pages
defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
      type: links
    values:
      layout: link_page
